"""Messaging application layer: ports + one authoritative capability per action (LAW-04)."""

from __future__ import annotations

from .capabilities import (
    CAP_CAMPAIGN_CREATE,
    CAP_CAMPAIGN_SCHEDULE,
    CAP_CAMPAIGN_SEND,
    CAP_CONSENT_UNSUBSCRIBE,
    CAP_TEMPLATE_PUBLISH,
    CAP_VERSION,
    MESSAGING_CAPABILITIES,
    RES_CAMPAIGN,
    CreateCampaign,
    CreateCampaignCommand,
    CreateCampaignResult,
    PublishTemplateVersion,
    PublishTemplateVersionCommand,
    PublishTemplateVersionResult,
    ScheduleCampaign,
    ScheduleCampaignCommand,
    ScheduleCampaignResult,
    SendCampaign,
    SendCampaignCommand,
    SendCampaignResult,
    Unsubscribe,
    UnsubscribeCommand,
    UnsubscribeResult,
)
from .ports import (
    MessageProviderPort,
    MessagingRepositoryPort,
    ProviderReceipt,
    SubmissionRequest,
)

__all__ = [
    "CAP_CAMPAIGN_CREATE",
    "CAP_CAMPAIGN_SCHEDULE",
    "CAP_CAMPAIGN_SEND",
    "CAP_CONSENT_UNSUBSCRIBE",
    "CAP_TEMPLATE_PUBLISH",
    "CAP_VERSION",
    "MESSAGING_CAPABILITIES",
    "RES_CAMPAIGN",
    "CreateCampaign",
    "CreateCampaignCommand",
    "CreateCampaignResult",
    "MessageProviderPort",
    "MessagingRepositoryPort",
    "ProviderReceipt",
    "PublishTemplateVersion",
    "PublishTemplateVersionCommand",
    "PublishTemplateVersionResult",
    "ScheduleCampaign",
    "ScheduleCampaignCommand",
    "ScheduleCampaignResult",
    "SendCampaign",
    "SendCampaignCommand",
    "SendCampaignResult",
    "SubmissionRequest",
    "Unsubscribe",
    "UnsubscribeCommand",
    "UnsubscribeResult",
]
