"""Extension application layer: ports + one authoritative capability per action (LAW-04)."""

from __future__ import annotations

from .capabilities import (
    CAP_APPLY_THEME,
    CAP_DISABLE,
    CAP_INSTALL,
    CAP_PUBLISH_CATALOG,
    CAP_UNINSTALL,
    CAP_UPGRADE,
    CAP_VERSION,
    EXTENSION_CAPABILITIES,
    RES_EXTENSION,
    ApplyTheme,
    ApplyThemeCommand,
    ApplyThemeResult,
    DisableExtension,
    DisableExtensionCommand,
    DisableExtensionResult,
    InstallExtension,
    InstallExtensionCommand,
    InstallExtensionResult,
    PublishCatalog,
    PublishCatalogCommand,
    PublishCatalogResult,
    UninstallExtension,
    UninstallExtensionCommand,
    UninstallExtensionResult,
    UpgradeExtension,
    UpgradeExtensionCommand,
    UpgradeExtensionResult,
)
from .ports import (
    ExtensionRegistryPort,
    ManifestKind,
    ManifestValidatorPort,
    SignatureVerifierPort,
    TrustAssertion,
)

__all__ = [
    "CAP_APPLY_THEME",
    "CAP_DISABLE",
    "CAP_INSTALL",
    "CAP_PUBLISH_CATALOG",
    "CAP_UNINSTALL",
    "CAP_UPGRADE",
    "CAP_VERSION",
    "EXTENSION_CAPABILITIES",
    "RES_EXTENSION",
    "ApplyTheme",
    "ApplyThemeCommand",
    "ApplyThemeResult",
    "DisableExtension",
    "DisableExtensionCommand",
    "DisableExtensionResult",
    "ExtensionRegistryPort",
    "InstallExtension",
    "InstallExtensionCommand",
    "InstallExtensionResult",
    "ManifestKind",
    "ManifestValidatorPort",
    "PublishCatalog",
    "PublishCatalogCommand",
    "PublishCatalogResult",
    "SignatureVerifierPort",
    "TrustAssertion",
    "UninstallExtension",
    "UninstallExtensionCommand",
    "UninstallExtensionResult",
    "UpgradeExtension",
    "UpgradeExtensionCommand",
    "UpgradeExtensionResult",
]
