"""northstar project generators — `make:module` / `make:plugin` / `make:theme` and recipes.

Stdlib-only (no new runtime deps). Scaffolds are deterministic and marked as generated;
they carry no domain behavior. The generators mirror the hexagonal layout in
``spec/reference/module-skeleton/`` and emit manifests that validate against the canonical
schemas in ``spec/contracts/schemas/`` (``module-manifest`` / ``plugin-manifest`` /
``theme-manifest``, manifest version ``1.0``). Deny-by-default: an existing target is never
overwritten.
"""

from __future__ import annotations

import json
import os
import re
from dataclasses import dataclass, field

# Canonical scaffold constants (spec/contracts/schemas + docs/19, docs/38).
IDENTIFIER_PATTERN = re.compile(r"^[a-z][a-z0-9]*(?:[._-][a-z0-9]+)*$")
SCAFFOLD_VERSION = "0.1.0"
FRAMEWORK_MINIMUM = "0.3.0"
FRAMEWORK_MAXIMUM_EXCLUSIVE = "1.0.0"
CONTRACT_API = "1.0.0"
DESIGN_SYSTEM = "northstar-ds@1.0.0"

# 64 hex zeros: a format-valid but obviously-placeholder digest for an unsigned scaffold.
_PLACEHOLDER_DIGEST = "sha256:" + "0" * 64


class GeneratorError(Exception):
    """Raised for invalid input or a refusal to overwrite an existing target."""


@dataclass(frozen=True, slots=True)
class GenerationResult:
    """Outcome of a single scaffold: what was created and where."""

    kind: str  # module | plugin | theme
    name: str
    target_dir: str
    files: tuple[str, ...] = field(default_factory=tuple)


@dataclass(frozen=True, slots=True)
class RecipePlan:
    """Structured, side-effect-free plan for a recipe add/remove request."""

    action: str  # add | remove
    recipe: str
    steps: tuple[str, ...] = field(default_factory=tuple)


def validate_name(name: str) -> str:
    """Return ``name`` if it is a valid lowercase identifier, else raise GeneratorError."""
    if not name or not IDENTIFIER_PATTERN.match(name):
        raise GeneratorError(
            f"invalid name {name!r}: expected pattern {IDENTIFIER_PATTERN.pattern}"
        )
    return name


def _display_name(name: str, suffix: str) -> str:
    words = re.split(r"[._-]+", name)
    return " ".join(w.capitalize() for w in words if w) + f" {suffix}"


def _class_name(name: str) -> str:
    words = re.split(r"[._-]+", name)
    return "".join(w.capitalize() for w in words if w) or "Item"


def _capability_segment(name: str) -> str:
    # Capability action segments allow only [a-z0-9-]; normalise separators.
    return re.sub(r"[^a-z0-9-]+", "-", name).strip("-") or "module"


def _ensure_absent(target_dir: str) -> None:
    if os.path.exists(target_dir):
        raise GeneratorError(f"refusing to overwrite existing target: {target_dir}")


def _write(files: list[str], base_dir: str, rel_path: str, content: str) -> None:
    abs_path = os.path.join(base_dir, rel_path)
    os.makedirs(os.path.dirname(abs_path), exist_ok=True)
    if os.path.exists(abs_path):
        raise GeneratorError(f"refusing to overwrite existing file: {abs_path}")
    with open(abs_path, "w", encoding="utf-8") as handle:
        handle.write(content if content.endswith("\n") else content + "\n")
    files.append(rel_path)


# ---- module scaffold ------------------------------------------------------------------


def _module_manifest(name: str) -> str:
    title = _display_name(name, "Module")
    capability = f"{_capability_segment(name)}.items.read"
    return (
        "# GENERATED by `northstar make:module`. Deterministic scaffold; edit intentionally.\n"
        "# Validates against spec/contracts/schemas/module-manifest.schema.json (manifest 1.0).\n"
        'manifest_version: "1.0"\n'
        f'module_id: "{name}"\n'
        f'name: "{title}"\n'
        f'version: "{SCAFFOLD_VERSION}"\n'
        f'description: "Generated Northstar module scaffold for {name}; replace with intent."\n'
        f'owner: "{name}-team"\n'
        'maturity: "experimental"\n'
        "framework_compatibility:\n"
        f'  minimum: "{FRAMEWORK_MINIMUM}"\n'
        f'  maximum_exclusive: "{FRAMEWORK_MAXIMUM_EXCLUSIVE}"\n'
        f'  contract_api: "{CONTRACT_API}"\n'
        "dependencies: []\n"
        "capabilities:\n"
        f'  - "{capability}"\n'
        "produced_events: []\n"
        "consumed_events: []\n"
        "data_ownership:\n"
        "  postgres_schemas:\n"
        f'    - "{name}"\n'
        "  object_prefixes:\n"
        f'    - "{name}/"\n'
        "  classifications:\n"
        '    - "internal"\n'
        "lifecycle:\n"
        "  migrations: true\n"
        "  health_checks:\n"
        '    - "migration_compatibility"\n'
        '  uninstall_policy: "retain"\n'
    )


def _module_domain_model(name: str) -> str:
    cls = _class_name(name)
    return (
        f'"""GENERATED by `northstar make:module`. Domain value objects for the {name} module.\n'
        "\n"
        "No framework, ORM or provider imports (LAW-12). Regenerate; edit intentionally.\n"
        '"""\n'
        "\n"
        "from __future__ import annotations\n"
        "\n"
        "from dataclasses import dataclass\n"
        "from uuid import UUID\n"
        "\n"
        "\n"
        "@dataclass(frozen=True, slots=True)\n"
        f"class {cls}Item:\n"
        '    """A domain value; persistence and transport concerns live in adapters."""\n'
        "\n"
        "    item_id: UUID\n"
        "    name: str\n"
        "\n"
        "    def __post_init__(self) -> None:\n"
        "        normalized = self.name.strip()\n"
        "        if not normalized:\n"
        '            raise ValueError("name must not be blank")\n'
        '        object.__setattr__(self, "name", normalized)\n'
    )


def _module_queries(name: str) -> str:
    cls = _class_name(name)
    return (
        f'"""GENERATED by `northstar make:module`. Application queries for the {name} module.\n'
        "\n"
        "Depends only on the domain via ports (LAW-04, hexagonal). Regenerate intentionally.\n"
        '"""\n'
        "\n"
        "from __future__ import annotations\n"
        "\n"
        "from dataclasses import dataclass\n"
        "from typing import Protocol\n"
        "from uuid import UUID\n"
        "\n"
        f"from ..domain.model import {cls}Item\n"
        "\n"
        "\n"
        f"class {cls}ItemReader(Protocol):\n"
        f"    async def get(self, item_id: UUID) -> {cls}Item | None: ...\n"
        "\n"
        "\n"
        "@dataclass(frozen=True, slots=True)\n"
        f"class Get{cls}Item:\n"
        "    item_id: UUID\n"
        "\n"
        "\n"
        f"class Get{cls}ItemHandler:\n"
        f"    def __init__(self, reader: {cls}ItemReader) -> None:\n"
        "        self._reader = reader\n"
        "\n"
        f"    async def handle(self, query: Get{cls}Item) -> {cls}Item | None:\n"
        "        return await self._reader.get(query.item_id)\n"
    )


def _module_domain_test(name: str) -> str:
    cls = _class_name(name)
    return (
        f'"""GENERATED test scaffold for the {name} module domain."""\n'
        "\n"
        "import os\n"
        "import sys\n"
        "from uuid import uuid4\n"
        "\n"
        "import pytest\n"
        "\n"
        "sys.path.insert(0, os.path.dirname(os.path.dirname(__file__)))\n"
        "\n"
        f"from domain.model import {cls}Item  # noqa: E402\n"
        "\n"
        "\n"
        "def test_name_is_normalized():\n"
        f'    item = {cls}Item(item_id=uuid4(), name="  {cls}  ")\n'
        f'    assert item.name == "{cls}"\n'
        "\n"
        "\n"
        "def test_blank_name_is_rejected():\n"
        '    with pytest.raises(ValueError, match="must not be blank"):\n'
        f'        {cls}Item(item_id=uuid4(), name="  ")\n'
    )


def _module_cms_contribution(name: str) -> str:
    payload = {
        "$schema": "https://schemas.northstar.example/cms-contribution/1.0.0",
        "module": name,
        "version": SCAFFOLD_VERSION,
        "navigation": [],
        "routes": [],
        "widgets": [],
        "actions": [],
        "requiredCapabilities": [],
    }
    return json.dumps(payload, indent=2)


def _generated_package_init(name: str, layer: str) -> str:
    return f'"""GENERATED {layer} package for the {name} module scaffold."""\n'


def _generated_readme(name: str, layer: str, note: str) -> str:
    return (
        f"# {_display_name(name, layer.capitalize())} (generated)\n"
        "\n"
        f"GENERATED by `northstar make:module`. {note}\n"
    )


def generate_module(name: str, base_dir: str) -> GenerationResult:
    """Scaffold ``modules/<name>/`` with the hexagonal layout and a valid ``module.yaml``."""
    validate_name(name)
    target_dir = os.path.join(base_dir, "modules", name)
    _ensure_absent(target_dir)

    root = os.path.join("modules", name)
    files: list[str] = []
    _write(files, base_dir, os.path.join(root, "module.yaml"), _module_manifest(name))
    _write(
        files,
        base_dir,
        os.path.join(root, "domain", "__init__.py"),
        _generated_package_init(name, "domain"),
    )
    _write(files, base_dir, os.path.join(root, "domain", "model.py"), _module_domain_model(name))
    _write(
        files,
        base_dir,
        os.path.join(root, "application", "__init__.py"),
        _generated_package_init(name, "application"),
    )
    _write(files, base_dir, os.path.join(root, "application", "queries.py"), _module_queries(name))
    _write(
        files,
        base_dir,
        os.path.join(root, "adapters", "__init__.py"),
        _generated_package_init(name, "adapters"),
    )
    _write(
        files,
        base_dir,
        os.path.join(root, "adapters", "README.md"),
        _generated_readme(name, "adapters", "Provider SDKs live here behind ports."),
    )
    _write(
        files,
        base_dir,
        os.path.join(root, "api", "__init__.py"),
        _generated_package_init(name, "api"),
    )
    _write(
        files,
        base_dir,
        os.path.join(root, "jobs", "__init__.py"),
        _generated_package_init(name, "jobs"),
    )
    _write(
        files,
        base_dir,
        os.path.join(root, "cms", "contribution.json"),
        _module_cms_contribution(name),
    )
    _write(
        files,
        base_dir,
        os.path.join(root, "migrations", "README.md"),
        _generated_readme(name, "migrations", f"This directory owns the {name} lineage."),
    )
    _write(
        files,
        base_dir,
        os.path.join(root, "contracts", "README.md"),
        _generated_readme(name, "contracts", "Versioned DTOs and capability descriptors."),
    )
    _write(
        files, base_dir, os.path.join(root, "tests", "test_domain.py"), _module_domain_test(name)
    )
    return GenerationResult("module", name, target_dir, tuple(files))


# ---- plugin scaffold ------------------------------------------------------------------


def _plugin_manifest(name: str) -> str:
    title = _display_name(name, "Plugin")
    framework = f">={FRAMEWORK_MINIMUM} <{FRAMEWORK_MAXIMUM_EXCLUSIVE}"
    return (
        "# GENERATED by `northstar make:plugin`. Deterministic scaffold; edit intentionally.\n"
        "# Validates against spec/contracts/schemas/plugin-manifest.schema.json (manifest 1.0).\n"
        "# Digest/signature/sbom/provenance are placeholders for an unsigned local scaffold.\n"
        'manifest_version: "1.0"\n'
        f'plugin_id: "{name}"\n'
        f'name: "{title}"\n'
        "publisher:\n"
        f'  id: "{name}-labs"\n'
        f'  name: "{_display_name(name, "Labs")}"\n'
        f'version: "{SCAFFOLD_VERSION}"\n'
        'license: "Apache-2.0"\n'
        'extension_type: "integration"\n'
        'required_trust_tier: "T1"\n'
        "compatibility:\n"
        f'  framework: "{framework}"\n'
        f'  contract_api: "{CONTRACT_API}"\n'
        "permissions: []\n"
        "network:\n"
        '  mode: "none"\n'
        "artifacts:\n"
        f'  package_digest: "{_PLACEHOLDER_DIGEST}"\n'
        '  signature: "unsigned-local-scaffold"\n'
        '  sbom: "sbom.spdx.json"\n'
        '  provenance: "provenance.json"\n'
        "lifecycle:\n"
        '  install: "recipes/install.yaml"\n'
        '  upgrade: "recipes/upgrade.yaml"\n'
        "  uninstall:\n"
        '    data_policy: "retain"\n'
    )


def generate_plugin(name: str, base_dir: str) -> GenerationResult:
    """Scaffold ``plugins/<name>/`` with a minimal valid plugin manifest."""
    validate_name(name)
    target_dir = os.path.join(base_dir, "plugins", name)
    _ensure_absent(target_dir)

    root = os.path.join("plugins", name)
    files: list[str] = []
    _write(files, base_dir, os.path.join(root, "plugin.yaml"), _plugin_manifest(name))
    _write(
        files,
        base_dir,
        os.path.join(root, "README.md"),
        _generated_readme(name, "plugin", "Declare only manifest-earned power (LAW-15)."),
    )
    return GenerationResult("plugin", name, target_dir, tuple(files))


# ---- theme scaffold -------------------------------------------------------------------


def _theme_manifest(name: str) -> str:
    title = _display_name(name, "Theme")
    return (
        "# GENERATED by `northstar make:theme`. Deterministic scaffold; edit intentionally.\n"
        "# Validates against spec/contracts/schemas/theme-manifest.schema.json (manifest 1.0).\n"
        'manifest_version: "1.0"\n'
        f'theme_id: "{name}"\n'
        f'name: "{title}"\n'
        f'version: "{SCAFFOLD_VERSION}"\n'
        "compatibility:\n"
        f'  design_system: "{DESIGN_SYSTEM}"\n'
        'tokens: "tokens.json"\n'
        "modes:\n"
        '  - "light"\n'
        '  - "dark"\n'
        "supports_rtl: true\n"
        "conformance:\n"
        '  wcag_target: "2.2-AA"\n'
        '  report_uri: "conformance/axe-report.json"\n'
    )


def _theme_tokens() -> str:
    payload = {
        "$schema": "https://schemas.northstar.example/theme-token/1.0.0",
        "color": {},
        "spacing": {},
        "typography": {},
    }
    return json.dumps(payload, indent=2)


def generate_theme(name: str, base_dir: str) -> GenerationResult:
    """Scaffold ``themes/<name>/`` with a minimal valid theme manifest."""
    validate_name(name)
    target_dir = os.path.join(base_dir, "themes", name)
    _ensure_absent(target_dir)

    root = os.path.join("themes", name)
    files: list[str] = []
    _write(files, base_dir, os.path.join(root, "theme.yaml"), _theme_manifest(name))
    _write(files, base_dir, os.path.join(root, "tokens.json"), _theme_tokens())
    _write(
        files,
        base_dir,
        os.path.join(root, "README.md"),
        _generated_readme(name, "theme", "Themes cannot change authorization or rules."),
    )
    return GenerationResult("theme", name, target_dir, tuple(files))


# ---- recipes (structured stub) --------------------------------------------------------


def plan_recipe(action: str, recipe: str) -> RecipePlan:
    """Return a structured, side-effect-free plan for a recipe add/remove request.

    Recipe application (registration, migrations, config writes) is owned by the
    distribution/installer runtime (docs/38) and is out of scope for this packet, so this
    reports an honest plan rather than a false success (NOT RUN != PASS).
    """
    if action not in ("add", "remove"):
        raise GeneratorError(f"invalid recipe action {action!r}: expected add|remove")
    validate_name(recipe)
    if action == "add":
        steps = (
            f"resolve recipe '{recipe}' from the signed catalog",
            "display requested permissions and compatibility",
            "apply declared files/config/module registration/migrations transactionally",
            "emit a change report and verification commands",
        )
    else:
        steps = (
            f"resolve installed recipe '{recipe}' and its ownership record",
            "compute reverse plan honoring declared removal behavior",
            "revert files/config/registration transactionally with evidence",
        )
    return RecipePlan(action, recipe, steps)
