"""Pure AI-governance domain: value objects, citation verifier, output guard (rule 60, LAW-02)."""

from __future__ import annotations

from .citations import (
    CitationReport,
    CitationVerdict,
    supports,
    verify_citation,
    verify_citations,
)
from .errors import (
    AiGovernanceError,
    AiInvariantViolation,
    ApprovalRequired,
    DataClassificationNotAllowed,
    MemoryNotFound,
    NoApprovedProviderError,
    ProhibitedActionError,
    PromptPackageImmutable,
    PromptPackageNotFound,
    RuntimePromptConcatenation,
    ToolArgumentInvalid,
    ToolBudgetExceeded,
    UnauthorizedToolError,
    UndeclaredToolError,
)
from .guard import GuardResult, guard_output
from .model import (
    ActorProfile,
    AIActorProfile,
    ApprovalTier,
    Citation,
    InteractionTrace,
    MemoryClass,
    MemoryPolicy,
    MemoryRecord,
    ModelProfile,
    PassageRef,
    PromptPackage,
    PromptPackageRef,
    SideEffect,
    TokenUsage,
    ToolApproval,
    ToolCallRecord,
    ToolDefinition,
    ToolGrant,
    UntrustedPassage,
    resolve_gateway,
    tier_for_side_effect,
)

__all__ = [
    "AIActorProfile",
    "ActorProfile",
    "AiGovernanceError",
    "AiInvariantViolation",
    "ApprovalRequired",
    "ApprovalTier",
    "Citation",
    "CitationReport",
    "CitationVerdict",
    "DataClassificationNotAllowed",
    "GuardResult",
    "InteractionTrace",
    "MemoryClass",
    "MemoryNotFound",
    "MemoryPolicy",
    "MemoryRecord",
    "ModelProfile",
    "NoApprovedProviderError",
    "PassageRef",
    "ProhibitedActionError",
    "PromptPackage",
    "PromptPackageImmutable",
    "PromptPackageNotFound",
    "PromptPackageRef",
    "RuntimePromptConcatenation",
    "SideEffect",
    "TokenUsage",
    "ToolApproval",
    "ToolArgumentInvalid",
    "ToolBudgetExceeded",
    "ToolCallRecord",
    "ToolDefinition",
    "ToolGrant",
    "UnauthorizedToolError",
    "UndeclaredToolError",
    "UntrustedPassage",
    "guard_output",
    "resolve_gateway",
    "supports",
    "tier_for_side_effect",
    "verify_citation",
    "verify_citations",
]
